#
###################################
# Site wide configuration
####################################
#
title: Larry
email: hello@larrycustod.io
description: Snippets of my life--from hacking up stuff on the web, weekend hobbies, to life events worth sharing on the internet 
url: https://larrycustod.io # the base hostname & protocol for your site
keywords: ["Programming", "JavaScript", "Python", "Data Structures", ""]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Larry Custodio
  avatar: #leonids-logo.png
  job: "Web Nerd"
  bio: "Frontend Engineer. I build websites, hack up quick scripts to make a more convenient web, and laugh at some 🔥memes." 
  email: hello@larrycustod.io
  disqus-shortname: larrycustodio
  google:
    plus: #username
    analytics: #TBD
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: larrycustodio #username
  linkedin: larry-custodio #username
  instagram: #username
  telegram: #username
